namespace Atari2600.Disassembler;

public static class InstructionParser {
    private static readonly Dictionary<int, InstructionDefinition> InstructionRegistry = new() {
                { 0x69, new InstructionDefinition(OperationType.Adc, AddressingMode.Immediate, 2) },
                { 0x65, new InstructionDefinition(OperationType.Adc, AddressingMode.ZeroPage, 2) },
                { 0x75, new InstructionDefinition(OperationType.Adc, AddressingMode.ZeroPageX, 2) },
                { 0x6D, new InstructionDefinition(OperationType.Adc, AddressingMode.Absolute, 3) },
                { 0x7D, new InstructionDefinition(OperationType.Adc, AddressingMode.AbsoluteX, 3) },
                { 0x79, new InstructionDefinition(OperationType.Adc, AddressingMode.AbsoluteY, 3) },
                { 0x61, new InstructionDefinition(OperationType.Adc, AddressingMode.IndexedIndirect, 2) },
                { 0x71, new InstructionDefinition(OperationType.Adc, AddressingMode.IndirectIndexed, 2) },
                { 0x29, new InstructionDefinition(OperationType.And, AddressingMode.Immediate, 2) },
                { 0x25, new InstructionDefinition(OperationType.And, AddressingMode.ZeroPage, 2) },
                { 0x35, new InstructionDefinition(OperationType.And, AddressingMode.ZeroPageX, 2) },
                { 0x2D, new InstructionDefinition(OperationType.And, AddressingMode.Absolute, 3) },
                { 0x3D, new InstructionDefinition(OperationType.And, AddressingMode.AbsoluteX, 3) },
                { 0x39, new InstructionDefinition(OperationType.And, AddressingMode.AbsoluteY, 3) },
                { 0x21, new InstructionDefinition(OperationType.And, AddressingMode.IndexedIndirect, 2) },
                { 0x31, new InstructionDefinition(OperationType.And, AddressingMode.IndirectIndexed, 2) },
                { 0x0A, new InstructionDefinition(OperationType.Asl, AddressingMode.Accumulator, 1) },
                { 0x06, new InstructionDefinition(OperationType.Asl, AddressingMode.ZeroPage, 2) },
                { 0x16, new InstructionDefinition(OperationType.Asl, AddressingMode.ZeroPageX, 2) },
                { 0x0E, new InstructionDefinition(OperationType.Asl, AddressingMode.Absolute, 3) },
                { 0x1E, new InstructionDefinition(OperationType.Asl, AddressingMode.AbsoluteX, 3) },
                { 0x90, new InstructionDefinition(OperationType.Bcc, AddressingMode.Relative, 2) },
                { 0xB0, new InstructionDefinition(OperationType.Bcs, AddressingMode.Relative, 2) },
                { 0xF0, new InstructionDefinition(OperationType.Beq, AddressingMode.Relative, 2) },
                { 0x24, new InstructionDefinition(OperationType.Bit, AddressingMode.ZeroPage, 2) },
                { 0x2C, new InstructionDefinition(OperationType.Bit, AddressingMode.Absolute, 3) },
                { 0x30, new InstructionDefinition(OperationType.Bmi, AddressingMode.Relative, 2) },
                { 0xD0, new InstructionDefinition(OperationType.Bne, AddressingMode.Relative, 2) },
                { 0x10, new InstructionDefinition(OperationType.Bpl, AddressingMode.Relative, 2) },
                { 0x00, new InstructionDefinition(OperationType.Brk, AddressingMode.Implicit, 1) },
                { 0x50, new InstructionDefinition(OperationType.Bvc, AddressingMode.Relative, 2) },
                { 0x70, new InstructionDefinition(OperationType.Bvs, AddressingMode.Relative, 2) },
                { 0x18, new InstructionDefinition(OperationType.Clc, AddressingMode.Implicit, 1) },
                { 0xD8, new InstructionDefinition(OperationType.Cld, AddressingMode.Implicit, 1) },
                { 0x58, new InstructionDefinition(OperationType.Cli, AddressingMode.Implicit, 1) },
                { 0xB8, new InstructionDefinition(OperationType.Clv, AddressingMode.Implicit, 1) },
                { 0xC9, new InstructionDefinition(OperationType.Cmp, AddressingMode.Immediate, 2) },
                { 0xC5, new InstructionDefinition(OperationType.Cmp, AddressingMode.ZeroPage, 2) },
                { 0xD5, new InstructionDefinition(OperationType.Cmp, AddressingMode.ZeroPageX, 2) },
                { 0xCD, new InstructionDefinition(OperationType.Cmp, AddressingMode.Absolute, 3) },
                { 0xDD, new InstructionDefinition(OperationType.Cmp, AddressingMode.AbsoluteX, 3) },
                { 0xD9, new InstructionDefinition(OperationType.Cmp, AddressingMode.AbsoluteY, 3) },
                { 0xC1, new InstructionDefinition(OperationType.Cmp, AddressingMode.IndexedIndirect, 2) },
                { 0xD1, new InstructionDefinition(OperationType.Cmp, AddressingMode.IndirectIndexed, 2) },
                { 0xE0, new InstructionDefinition(OperationType.Cpx, AddressingMode.Immediate, 2) },
                { 0xE4, new InstructionDefinition(OperationType.Cpx, AddressingMode.ZeroPage, 2) },
                { 0xEC, new InstructionDefinition(OperationType.Cpx, AddressingMode.Absolute, 3) },
                { 0xC0, new InstructionDefinition(OperationType.Cpy, AddressingMode.Immediate, 2) },
                { 0xC4, new InstructionDefinition(OperationType.Cpy, AddressingMode.ZeroPage, 2) },
                { 0xCC, new InstructionDefinition(OperationType.Cpy, AddressingMode.Absolute, 3) },
                { 0xC6, new InstructionDefinition(OperationType.Dec, AddressingMode.ZeroPage, 2) },
                { 0xD6, new InstructionDefinition(OperationType.Dec, AddressingMode.ZeroPageX, 2) },
                { 0xCE, new InstructionDefinition(OperationType.Dec, AddressingMode.Absolute, 3) },
                { 0xDE, new InstructionDefinition(OperationType.Dec, AddressingMode.AbsoluteX, 3) },
                { 0xCA, new InstructionDefinition(OperationType.Dex, AddressingMode.Implicit, 1) },
                { 0x88, new InstructionDefinition(OperationType.Dey, AddressingMode.Implicit, 1) },
                { 0x49, new InstructionDefinition(OperationType.Eor, AddressingMode.Immediate, 2) },
                { 0x45, new InstructionDefinition(OperationType.Eor, AddressingMode.ZeroPage, 2) },
                { 0x55, new InstructionDefinition(OperationType.Eor, AddressingMode.ZeroPageX, 2) },
                { 0x4D, new InstructionDefinition(OperationType.Eor, AddressingMode.Absolute, 3) },
                { 0x5D, new InstructionDefinition(OperationType.Eor, AddressingMode.AbsoluteX, 3) },
                { 0x59, new InstructionDefinition(OperationType.Eor, AddressingMode.AbsoluteY, 3) },
                { 0x41, new InstructionDefinition(OperationType.Eor, AddressingMode.IndexedIndirect, 2) },
                { 0x51, new InstructionDefinition(OperationType.Eor, AddressingMode.IndirectIndexed, 2) },
                { 0xE6, new InstructionDefinition(OperationType.Inc, AddressingMode.ZeroPage, 2) },
                { 0xF6, new InstructionDefinition(OperationType.Inc, AddressingMode.ZeroPageX, 2) },
                { 0xEE, new InstructionDefinition(OperationType.Inc, AddressingMode.Absolute, 3) },
                { 0xFE, new InstructionDefinition(OperationType.Inc, AddressingMode.AbsoluteX, 3) },
                { 0xE8, new InstructionDefinition(OperationType.Inx, AddressingMode.Implicit, 1) },
                { 0xC8, new InstructionDefinition(OperationType.Iny, AddressingMode.Implicit, 1) },
                { 0x4C, new InstructionDefinition(OperationType.Jmp, AddressingMode.Absolute, 3) },
                { 0x6C, new InstructionDefinition(OperationType.Jmp, AddressingMode.Indirect, 3) },
                { 0x20, new InstructionDefinition(OperationType.Jsr, AddressingMode.Absolute, 3) },
                { 0xA9, new InstructionDefinition(OperationType.Lda, AddressingMode.Immediate, 2) },
                { 0xA5, new InstructionDefinition(OperationType.Lda, AddressingMode.ZeroPage, 2) },
                { 0xB5, new InstructionDefinition(OperationType.Lda, AddressingMode.ZeroPageX, 2) },
                { 0xAD, new InstructionDefinition(OperationType.Lda, AddressingMode.Absolute, 3) },
                { 0xBD, new InstructionDefinition(OperationType.Lda, AddressingMode.AbsoluteX, 3) },
                { 0xB9, new InstructionDefinition(OperationType.Lda, AddressingMode.AbsoluteY, 3) },
                { 0xA1, new InstructionDefinition(OperationType.Lda, AddressingMode.IndexedIndirect, 2) },
                { 0xB1, new InstructionDefinition(OperationType.Lda, AddressingMode.IndirectIndexed, 2) },
                { 0xA2, new InstructionDefinition(OperationType.Ldx, AddressingMode.Immediate, 2) },
                { 0xA6, new InstructionDefinition(OperationType.Ldx, AddressingMode.ZeroPage, 2) },
                { 0xB6, new InstructionDefinition(OperationType.Ldx, AddressingMode.ZeroPageY, 2) },
                { 0xAE, new InstructionDefinition(OperationType.Ldx, AddressingMode.Absolute, 3) },
                { 0xBE, new InstructionDefinition(OperationType.Ldx, AddressingMode.AbsoluteY, 3) },
                { 0xA0, new InstructionDefinition(OperationType.Ldy, AddressingMode.Immediate, 2) },
                { 0xA4, new InstructionDefinition(OperationType.Ldy, AddressingMode.ZeroPage, 2) },
                { 0xB4, new InstructionDefinition(OperationType.Ldy, AddressingMode.ZeroPageX, 2) },
                { 0xAC, new InstructionDefinition(OperationType.Ldy, AddressingMode.Absolute, 3) },
                { 0xBC, new InstructionDefinition(OperationType.Ldy, AddressingMode.AbsoluteX, 3) },
                { 0x4A, new InstructionDefinition(OperationType.Lsr, AddressingMode.Accumulator, 1) },
                { 0x46, new InstructionDefinition(OperationType.Lsr, AddressingMode.ZeroPage, 2) },
                { 0x56, new InstructionDefinition(OperationType.Lsr, AddressingMode.ZeroPageX, 2) },
                { 0x4E, new InstructionDefinition(OperationType.Lsr, AddressingMode.Absolute, 3) },
                { 0x5E, new InstructionDefinition(OperationType.Lsr, AddressingMode.AbsoluteX, 3) },
                { 0xEA, new InstructionDefinition(OperationType.Nop, AddressingMode.Implicit, 1) },
                { 0x09, new InstructionDefinition(OperationType.Ora, AddressingMode.Immediate, 2) },
                { 0x05, new InstructionDefinition(OperationType.Ora, AddressingMode.ZeroPage, 2) },
                { 0x15, new InstructionDefinition(OperationType.Ora, AddressingMode.ZeroPageX, 2) },
                { 0x0D, new InstructionDefinition(OperationType.Ora, AddressingMode.Absolute, 3) },
                { 0x1D, new InstructionDefinition(OperationType.Ora, AddressingMode.AbsoluteX, 3) },
                { 0x19, new InstructionDefinition(OperationType.Ora, AddressingMode.AbsoluteY, 3) },
                { 0x01, new InstructionDefinition(OperationType.Ora, AddressingMode.IndexedIndirect, 2) },
                { 0x11, new InstructionDefinition(OperationType.Ora, AddressingMode.IndirectIndexed, 2) },
                { 0x48, new InstructionDefinition(OperationType.Pha, AddressingMode.Implicit, 1) },
                { 0x08, new InstructionDefinition(OperationType.Php, AddressingMode.Implicit, 1) },
                { 0x68, new InstructionDefinition(OperationType.Pla, AddressingMode.Implicit, 1) },
                { 0x28, new InstructionDefinition(OperationType.Plp, AddressingMode.Implicit, 1) },
                { 0x2A, new InstructionDefinition(OperationType.Rol, AddressingMode.Accumulator, 1) },
                { 0x26, new InstructionDefinition(OperationType.Rol, AddressingMode.ZeroPage, 2) },
                { 0x36, new InstructionDefinition(OperationType.Rol, AddressingMode.ZeroPageX, 2) },
                { 0x2E, new InstructionDefinition(OperationType.Rol, AddressingMode.Absolute, 3) },
                { 0x3E, new InstructionDefinition(OperationType.Rol, AddressingMode.AbsoluteX, 3) },
                { 0x6A, new InstructionDefinition(OperationType.Ror, AddressingMode.Accumulator, 1) },
                { 0x66, new InstructionDefinition(OperationType.Ror, AddressingMode.ZeroPage, 2) },
                { 0x76, new InstructionDefinition(OperationType.Ror, AddressingMode.ZeroPageX, 2) },
                { 0x6E, new InstructionDefinition(OperationType.Ror, AddressingMode.Absolute, 3) },
                { 0x7E, new InstructionDefinition(OperationType.Ror, AddressingMode.AbsoluteX, 3) },
                { 0x40, new InstructionDefinition(OperationType.Rti, AddressingMode.Implicit, 1) },
                { 0x60, new InstructionDefinition(OperationType.Rts, AddressingMode.Implicit, 1) },
                { 0xE9, new InstructionDefinition(OperationType.Sbc, AddressingMode.Immediate, 2) },
                { 0xE5, new InstructionDefinition(OperationType.Sbc, AddressingMode.ZeroPage, 2) },
                { 0xF5, new InstructionDefinition(OperationType.Sbc, AddressingMode.ZeroPageX, 2) },
                { 0xED, new InstructionDefinition(OperationType.Sbc, AddressingMode.Absolute, 3) },
                { 0xFD, new InstructionDefinition(OperationType.Sbc, AddressingMode.AbsoluteX, 3) },
                { 0xF9, new InstructionDefinition(OperationType.Sbc, AddressingMode.AbsoluteY, 3) },
                { 0xE1, new InstructionDefinition(OperationType.Sbc, AddressingMode.IndexedIndirect, 2) },
                { 0xF1, new InstructionDefinition(OperationType.Sbc, AddressingMode.IndirectIndexed, 2) },
                { 0x38, new InstructionDefinition(OperationType.Sec, AddressingMode.Implicit, 1) },
                { 0xF8, new InstructionDefinition(OperationType.Sed, AddressingMode.Implicit, 1) },
                { 0x78, new InstructionDefinition(OperationType.Sei, AddressingMode.Implicit, 1) },
                { 0x85, new InstructionDefinition(OperationType.Sta, AddressingMode.ZeroPage, 2) },
                { 0x95, new InstructionDefinition(OperationType.Sta, AddressingMode.ZeroPageX, 2) },
                { 0x8D, new InstructionDefinition(OperationType.Sta, AddressingMode.Absolute, 3) },
                { 0x9D, new InstructionDefinition(OperationType.Sta, AddressingMode.AbsoluteX, 3) },
                { 0x99, new InstructionDefinition(OperationType.Sta, AddressingMode.AbsoluteY, 3) },
                { 0x81, new InstructionDefinition(OperationType.Sta, AddressingMode.IndexedIndirect, 2) },
                { 0x91, new InstructionDefinition(OperationType.Sta, AddressingMode.IndirectIndexed, 2) },
                { 0x86, new InstructionDefinition(OperationType.Stx, AddressingMode.ZeroPage, 2) },
                { 0x96, new InstructionDefinition(OperationType.Stx, AddressingMode.ZeroPageY, 2) },
                { 0x8E, new InstructionDefinition(OperationType.Stx, AddressingMode.Absolute, 3) },
                { 0x84, new InstructionDefinition(OperationType.Sty, AddressingMode.ZeroPage, 2) },
                { 0x94, new InstructionDefinition(OperationType.Sty, AddressingMode.ZeroPageX, 2) },
                { 0x8C, new InstructionDefinition(OperationType.Sty, AddressingMode.Absolute, 3) },
                { 0xAA, new InstructionDefinition(OperationType.Tax, AddressingMode.Implicit, 1) },
                { 0xA8, new InstructionDefinition(OperationType.Tay, AddressingMode.Implicit, 1) },
                { 0xBA, new InstructionDefinition(OperationType.Tsx, AddressingMode.Implicit, 1) },
                { 0x8A, new InstructionDefinition(OperationType.Txa, AddressingMode.Implicit, 1) },
                { 0x9A, new InstructionDefinition(OperationType.Txs, AddressingMode.Implicit, 1) },
                { 0x98, new InstructionDefinition(OperationType.Tya, AddressingMode.Implicit, 1) }
            };

    public static Instruction? ParseInstruction(Stream source) {
        int OpCode = source.ReadByte();
        if (OpCode < 0) {
            // at end of stream
            return null;
        }

        if (!InstructionParser.InstructionRegistry.ContainsKey(OpCode)) {
            // todo: show warning?
            // throw new ApplicationException("Invalid OpCode: " + OpCode.ToString("X2"));
            // when the opcode doesnt exist, actually just skip it and let it be "data in memory"
            return new Instruction((byte)OpCode, OperationType.Nop, AddressingMode.Implicit, null);
        }

        InstructionDefinition Match = InstructionParser.InstructionRegistry[OpCode];
        byte[]? NextBytes = null;
        if (Match.TotalByteCount > 1) {
            NextBytes = new byte[Match.TotalByteCount - 1];
            int Read = source.Read(NextBytes);
            if (Read < NextBytes.Length) throw new IOException("Could not read " + NextBytes + " byte(s) from stream");
        }

        return new Instruction((byte)OpCode, Match.OperationType, Match.AddressingMode, NextBytes);
    }

    private record InstructionDefinition(
        OperationType OperationType,
        AddressingMode AddressingMode,
        int TotalByteCount);
} //brk,1793